In [1]:
import pandas as pd
import numpy as np
from pathlib import Path # Importar Path para manejar rutas de archivos

## Cargar datos

In [2]:
# definir la ruta del archivo CSV
RAW_DATA_PATH = Path("../data/raw/enero/Facturas")  # Ruta de la carpeta raw

#lista de archivos CSV en la carpeta raw
csv_files = list(RAW_DATA_PATH.glob("*.csv")) 
csv_files

# cargar el archivo CSV en un DataFrame de pandas

[PosixPath('../data/raw/enero/Facturas/d1_11_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_03_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_14_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_19_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/mercacentro_06_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_03_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_15_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/mercacentro_21_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_27_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_09_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_21_enero.csv')]

In [3]:
file_path = csv_files[7]  # Seleccionar el primer archivo CSV
df = pd.read_csv(file_path)
df.head()

,Item,Descripcion,Cantidad,Unidad,Valor_Unitario,Total
0,1,LECHE MERCACENTRO LV S.DES 6x1000 ml,2,paq,22300,44600

### columnas de todos los dataframe

In [4]:
# iterar sobre los archivos CSV y cargar cada uno en un DataFrame de pandas
for file in csv_files:
    df_temp = pd.read_csv(file)
    print(file.name)
    print(df_temp.columns)
    print("------")

d1_11_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
d1_03_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
surtiplaza_14_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
surtiplaza_19_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
mercacentro_06_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
surtiplaza_03_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
d1_15_enero.csv
Index(['Ref', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
mercacentro_21_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
d1_27_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
surtiplaza_09_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
d1_21_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------

# Normalización de datos

In [5]:

# Definir una lista para almacenar los DataFrames
dfs = []

# Diccionario para mapear nombres de meses en español a números
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

# Iterar sobre los archivos CSV, cargar cada uno en un DataFrame y agregar columnas adicionales

for file in csv_files:
    df_temp = pd.read_csv(file)
    
    tienda_name = file.stem # Obtener el nombre del archivo sin la extensión
    partes = tienda_name.split("_") # Dividir el nombre del archivo en partes
    
    tienda = partes[0] # Nombre de la tienda
    dia = int(partes[1]) # Día como entero
    mes_nombre = partes[2].lower() # Nombre del mes en minúsculas
    
    mes_num = meses[mes_nombre] # Convertir el nombre del mes a número usando el diccionario
    año = 2026

    # Crear fecha real
    fecha_completa = pd.Timestamp(year=año, month=mes_num, day=dia)

    # Agregar columnas
    df_temp["tienda"] = tienda
    df_temp["fecha"] = fecha_completa
    df_temp["mes"] = mes_num
    df_temp["año"] = año

    dfs.append(df_temp)
    print(df_temp.columns)  # Verificar que la nueva columna se haya agregado correctamente
    print("------")

Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Ref', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------

In [6]:
dfs[7].head()

,Item,Descripcion,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,1,LECHE MERCACENTRO LV S.DES 6x1000 ml,2,paq,22300,44600,mercacentro,2026-01-21,1,2026

### normalizar nombres de columnas

In [7]:
# normalizar nombres de columnas para que sean iguales en todos los DataFrames 
for df in dfs:
    df.rename(columns={
        "Precio": "Valor_Unitario",
        "Descripcion": "Producto",
    }, inplace=True)

dfs[6].head()

,Ref,Producto,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,1,Queso holandés,1,und,8300,8300,d1,2026-01-15,1,2026
1,2,Quesillo bloque,1,und,9990,9990,d1,2026-01-15,1,2026
2,3,Tomates enteros,1,und,4350,4350,d1,2026-01-15,1,2026
3,4,Topping mediano,2,und,4950,9900,d1,2026-01-15,1,2026
4,5,Chips de vegetales,2,und,2990,5980,d1,2026-01-15,1,2026

In [8]:
# Eliminar columnas innecesarias "Ref" y "Item" si existen en los DataFrames
for df in dfs:
    if "Ref" in df.columns:
        df.drop(columns=["Ref"], inplace=True)
    if "Item" in df.columns:
        df.drop(columns=["Item"], inplace=True)

for df in dfs:
    print(df.columns)  # Verificar que las columnas se hayan eliminado correctamente
    print("------")

Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------

In [9]:
# mostrar el indice de los dataframes que no tienen la columna total
for i, df in enumerate(dfs):
    if "Total" not in df.columns:
        print(f"DataFrame en índice {i} no tiene la columna 'Total'")

DataFrame en índice 0 no tiene la columna 'Total'
DataFrame en índice 1 no tiene la columna 'Total'
DataFrame en índice 4 no tiene la columna 'Total'
DataFrame en índice 5 no tiene la columna 'Total'
DataFrame en índice 9 no tiene la columna 'Total'

In [10]:
dfs[0].head()

,Producto,Cantidad,Unidad,Valor_Unitario,tienda,fecha,mes,año
0,Yogurt griego,1,und,7300,d1,2026-01-11,1,2026
1,Jamón Pietrán,1,und,13650,d1,2026-01-11,1,2026
2,Queso parmesano,1,und,14850,d1,2026-01-11,1,2026
3,Quesillo tajado,1,und,9990,d1,2026-01-11,1,2026
4,Topping mediano,4,und,19800,d1,2026-01-11,1,2026

In [11]:
# cambiar el nombre de la columna "valor_unitario" a "Total" en el DataFrame que no tiene la columna "Total"
for df in dfs:
    if "Total" not in df.columns and "Valor_Unitario" in df.columns:
        df.rename(columns={"Valor_Unitario": "Total"}, inplace=True)

dfs[0].head()

          Producto  Cantidad Unidad  Total tienda      fecha  mes   año
0    Yogurt griego         1    und   7300     d1 2026-01-11    1  2026
1    Jamón Pietrán         1    und  13650     d1 2026-01-11    1  2026
2  Queso parmesano         1    und  14850     d1 2026-01-11    1  2026
3  Quesillo tajado         1    und   9990     d1 2026-01-11    1  2026
4  Topping mediano         4    und  19800     d1 2026-01-11    1  2026

In [12]:

# agregar la columna "valor_unitario" a los DataFrames que no tienen la columna "Valor_Unitario" y calcular su valor dividiendo la columna "Total" entre la cantidad de productos
for df in dfs:
    if "Valor_Unitario" not in df.columns and "Total" in df.columns and "Cantidad" in df.columns:
        df["Valor_Unitario"] = df["Total"] / df["Cantidad"] 

dfs[0].head()

,Producto,Cantidad,Unidad,Total,tienda,fecha,mes,año,Valor_Unitario
0,Yogurt griego,1,und,7300,d1,2026-01-11,1,2026,7300.0
1,Jamón Pietrán,1,und,13650,d1,2026-01-11,1,2026,13650.0
2,Queso parmesano,1,und,14850,d1,2026-01-11,1,2026,14850.0
3,Quesillo tajado,1,und,9990,d1,2026-01-11,1,2026,9990.0
4,Topping mediano,4,und,19800,d1,2026-01-11,1,2026,4950.0

In [13]:
for df in dfs:
    print(df.columns)  # Verificar que la nueva columna se haya agregado correctamente
    print("------")

Index(['Producto', 'Cantidad', 'Unidad', 'Total', 'tienda', 'fecha', 'mes',
       'año', 'Valor_Unitario'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Total', 'tienda', 'fecha', 'mes',
       'año', 'Valor_Unitario'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Total', 'tienda', 'fecha', 'mes',
       'año', 'Valor_Unitario'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Total', 'tienda', 'fecha', 'mes',
       'año', 'Valor_Unitario'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Total', 'tienda', 'fecha', 'mes',
       'año', 'Valor_Unitario'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------

In [14]:
# ordenar las columnas de cada DataFrame en el mismo orden
column_order = ["Producto", "Cantidad", "Unidad", "Valor_Unitario", "Total", "tienda", "fecha", "mes", "año"]

dfs = [df[column_order] for df in dfs]


for df in dfs:
    print(df.columns)  # Verificar que las columnas estén en el mismo orden
    print("------")

Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------

In [15]:
COLUMNAS_FINALES = [
    "producto",
    "precio_unitario",
    "cantidad",
    "total",
    "tienda",
    "fecha",
    "categoria"
]

# CONTATENAR LOS DATAFRAMES

In [16]:
# Concatenar todos los DataFrames en uno solo
df_final = pd.concat(dfs, ignore_index=True)
df_final.head(100)

,Producto,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,Yogurt griego,1.00,und,7300.000000,7300,d1,2026-01-11,1,2026
1,Jamón Pietrán,1.00,und,13650.000000,13650,d1,2026-01-11,1,2026
2,Queso parmesano,1.00,und,14850.000000,14850,d1,2026-01-11,1,2026
3,Quesillo tajado,1.00,und,9990.000000,9990,d1,2026-01-11,1,2026
4,Topping mediano,4.00,und,4950.000000,19800,d1,2026-01-11,1,2026
...,...,...,...,...,...,...,...,...,...
89,Champiñón tajado 150g,1.00,und,5990.000000,5990,surtiplaza,2026-01-09,1,2026
90,Papaya común,2.57,kg,3380.155642,8687,surtiplaza,2026-01-09,1,2026
91,YOGURT GRIEGO,1.00,und,7300.000000,7300,d1,2026-01-21,1,2026
92,topping,3.00,und,14850.000000,14850,d1,2026-01-21,1,2026
93,QUESO HOLANDES,1.00,und,8300.000000,8300,d1,2026-01-21,1,2026

In [17]:
# Filtrar donde la columna "valor_unitario" es igual a "total" y la cantidad es diferente de 1
df_filtrado = df_final[(df_final["Valor_Unitario"] == df_final["Total"]) & (df_final["Cantidad"] != 1)]

# ajustar el valor de la columna "valor_unitario" dividiendo el valor de la columna "total" entre la columna "cantidad" en el DataFrame filtrado
df_final.loc[df_filtrado.index, "Valor_Unitario"] = df_filtrado["Total"] / df_filtrado["Cantidad"]

df_final.head(100)

,Producto,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,Yogurt griego,1.00,und,7300.000000,7300,d1,2026-01-11,1,2026
1,Jamón Pietrán,1.00,und,13650.000000,13650,d1,2026-01-11,1,2026
2,Queso parmesano,1.00,und,14850.000000,14850,d1,2026-01-11,1,2026
3,Quesillo tajado,1.00,und,9990.000000,9990,d1,2026-01-11,1,2026
4,Topping mediano,4.00,und,4950.000000,19800,d1,2026-01-11,1,2026
...,...,...,...,...,...,...,...,...,...
89,Champiñón tajado 150g,1.00,und,5990.000000,5990,surtiplaza,2026-01-09,1,2026
90,Papaya común,2.57,kg,3380.155642,8687,surtiplaza,2026-01-09,1,2026
91,YOGURT GRIEGO,1.00,und,7300.000000,7300,d1,2026-01-21,1,2026
92,topping,3.00,und,4950.000000,14850,d1,2026-01-21,1,2026
93,QUESO HOLANDES,1.00,und,8300.000000,8300,d1,2026-01-21,1,2026

In [18]:
#  convertir lower case la columna "producto" en el DataFrame final
df_final["Producto"] = df_final["Producto"].str.lower()
df_final.head(100)

,Producto,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,yogurt griego,1.00,und,7300.000000,7300,d1,2026-01-11,1,2026
1,jamón pietrán,1.00,und,13650.000000,13650,d1,2026-01-11,1,2026
2,queso parmesano,1.00,und,14850.000000,14850,d1,2026-01-11,1,2026
3,quesillo tajado,1.00,und,9990.000000,9990,d1,2026-01-11,1,2026
4,topping mediano,4.00,und,4950.000000,19800,d1,2026-01-11,1,2026
...,...,...,...,...,...,...,...,...,...
89,champiñón tajado 150g,1.00,und,5990.000000,5990,surtiplaza,2026-01-09,1,2026
90,papaya común,2.57,kg,3380.155642,8687,surtiplaza,2026-01-09,1,2026
91,yogurt griego,1.00,und,7300.000000,7300,d1,2026-01-21,1,2026
92,topping,3.00,und,4950.000000,14850,d1,2026-01-21,1,2026
93,queso holandes,1.00,und,8300.000000,8300,d1,2026-01-21,1,2026

In [19]:
# decimales de valor_unitario y total a 2 decimales
df_final["Valor_Unitario"] = df_final["Valor_Unitario"].round(2)
df_final["Total"] = df_final["Total"].round(2)
df_final.head(100)

,Producto,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,yogurt griego,1.00,und,7300.00,7300,d1,2026-01-11,1,2026
1,jamón pietrán,1.00,und,13650.00,13650,d1,2026-01-11,1,2026
2,queso parmesano,1.00,und,14850.00,14850,d1,2026-01-11,1,2026
3,quesillo tajado,1.00,und,9990.00,9990,d1,2026-01-11,1,2026
4,topping mediano,4.00,und,4950.00,19800,d1,2026-01-11,1,2026
...,...,...,...,...,...,...,...,...,...
89,champiñón tajado 150g,1.00,und,5990.00,5990,surtiplaza,2026-01-09,1,2026
90,papaya común,2.57,kg,3380.16,8687,surtiplaza,2026-01-09,1,2026
91,yogurt griego,1.00,und,7300.00,7300,d1,2026-01-21,1,2026
92,topping,3.00,und,4950.00,14850,d1,2026-01-21,1,2026
93,queso holandes,1.00,und,8300.00,8300,d1,2026-01-21,1,2026

In [24]:
df_final.loc[df_final.index[62:66]]

,Producto,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
62,queso holandés,1.0,und,8300.0,8300,d1,2026-01-15,1,2026
63,quesillo bloque,1.0,und,9990.0,9990,d1,2026-01-15,1,2026
64,tomates enteros,1.0,und,4350.0,4350,d1,2026-01-15,1,2026
65,topping mediano,2.0,und,4950.0,9900,d1,2026-01-15,1,2026

In [21]:
# Total gastado en cada tienda
total_por_tienda = df_final.groupby("tienda")["Total"].sum().reset_index()
total_por_tienda.rename(columns={"Total": "Total_Gastado"}, inplace=True)
total_por_tienda.head()

        tienda  Total_Gastado
0           d1         403910
1  mercacentro         106000
2   surtiplaza         527399

In [23]:
# total gastado por mes
total_por_mes = df_final.groupby("mes")["Total"].sum().reset_index()
total_por_mes.rename(columns={"Total": "Total_Gastado"}, inplace=True)
total_por_mes.head()

   mes  Total_Gastado
0    1        1037309